spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
            database: 1
            host: redis
            pool:
                max-active: 20
server:
    port: 8780 #启动端口
#
zuul:
  routes:
    back:
      path: /data-geode/**
      serviceId: geode

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management: 
    security: 
        enabled: false

feign:
  hystrix:
    enabled: true
