spring:
  application:
    name: geode
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8762

management.security.enabled: false

geode:
  cache:
    server:
      host: localhost
      port: 40404
    log:
      level: config

swagger:
    basepackage: com.zw.geode
    service:
        name: Module
        description: 模块APIs文档
        developer: 中位科技开发团队
