spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
            database: 1
            host: redis
            pool:
                max-active: 20
server:
    port: 8763 #启动端口
#
zuul:
  routes:
    back:
      path: /back/**
      serviceId: zw-geode

ribbon:
  eureka:
    enabled: true

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://zw-register:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://register:8761/eureka/


security:
    user:
        name: admin
        password: admin
        role: USER
