server:
    port: 8764

security:
    user:
        name: whb
        password: 123456
        role: USER
eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://zw-register:8761/eureka/
          


spring: 
    boot: 
        admin: 
            routes: 
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
            turbine:
                clusters: default
                location: turbine 

