server:
    port: 8762

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management: 
  security: 
    enabled: false


spring: 
  boot: 
    admin: 
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

spring:
  boot:
    admin: 
      turbine:
        clusters: default
        location: turbine

